const colorConfig = {
  background: 'var(--background)',
  backgroundChild: 'var(--backgroundChild)',
  backgroundInput: 'var(--backgroundInput)',
  backgroundInputHover: 'var(--backgroundInputHover)',
  backgroundActive: 'var(--backgroundActive)',
  backgroundModal: 'var(--backgroundModal)',
  backgroundWrapper: 'var(--backgroundWrapper)',
  backgroundInputSpecial: 'var(--backgroundInputSpecial)',
  backgroundLoading: 'var(--backgroundLoading)',
  textSubSwap: 'var(--textSubSwap)',
  textContentSpecial: 'var(--textContentSpecial)',
  textTitleSpecial: 'var(--textTitleSpecial)',
  textTitle: 'var(--textTitle)',
  textTitleReverse: 'var(--textTitleReverse)',
  textTitleActive: 'var(--textTitleActive)',
  textContent: 'var(--textContent)',
  textButtonLight: 'var(--textButtonLight)',
  textContentPopup: 'var(--textContentPopup)',
  textSub: 'var(--textSub)',
  textDisable: 'var(--textDisable)',
  textLink: 'var(--textLink)',
  textLinkHover: 'var(--textLinkHover)',
  textPlaceholder: 'var(--textPlaceholder)',
  dividerColor: 'var(--dividerColor)',
  dividerColorBgInput: 'var(--dividerColorBgInput)',
  dividerColorDefault: 'var(--dividerColorDefault)',
  primaryButton: 'var(--primaryButton)',
  primaryButtonHover: 'var(--primaryButtonHover)',
  disableButton: 'var(--disableButton)',
  error: 'var(--error)',
  warning: 'var(--warning)',
  success: 'var(--success)',
  info: 'var(--info)',
  errorHover: 'var(--errorHover)',
  warningHover: 'var(--warningHover)',
  successHover: 'var(--successHover)',
  infoHover: 'var(--infoHover)',
  errorBackground: 'var(--errorBackground)',
  warningBackground: 'var(--warningBackground)',
  successBackground: 'var(--successBackground)',
  infoBackground: 'var(--infoBackground)',
}

export default colorConfig
