export const RANDOM_SPEECH = [
  "This is a simple paragraph",
  "Today, the weather is sunny and warm. The sky is clear, and there is a gentle breeze. It's a perfect day for a walk in the park or a picnic with friends.",
  "The beach was crowded with people enjoying the sun. Children were building sandcastles, and the sound of the waves was soothing. It was a relaxing day by the sea.",
  "I love painting. It allows me to express my creativity and relax. I enjoy experimenting with colors and different techniques to create unique pieces of art.",
  "The zoo was full of fascinating animals. I saw lions, elephants, and monkeys. Watching the animals interact with each other was both educational and entertaining.",
  "Walking in the park is refreshing. The trees provide shade, and the flowers are in full bloom. It's a great place to clear your mind and enjoy nature.",
  "Cooking dinner is a rewarding experience. I enjoy trying new recipes and flavors. Preparing a meal from scratch gives me a sense of accomplishment.",
  "The museum was filled with interesting exhibits. I learned about ancient civilizations and saw beautiful works of art. It was an enlightening experience.",
  "Reading a book is a great way to escape reality. It allows you to explore new worlds and meet interesting characters. It's a wonderful way to spend an afternoon.",
  "Gardening is a peaceful hobby. Planting seeds and watching them grow into beautiful flowers is satisfying. It connects you with nature and provides fresh air.",
  "School is a place for learning and growth. Each day brings new challenges and opportunities to expand your knowledge. It's important to stay curious and engaged.",
  "Playing sports is a fun way to stay active. It teaches teamwork and discipline. Whether it's soccer, basketball, or tennis, sports are a great way to stay fit.",
  "Family gatherings are special occasions. It's a time to catch up with relatives and enjoy good food. The laughter and stories shared create lasting memories.",
  "The library is a quiet place filled with knowledge. It's a great resource for research and finding new books to read. The atmosphere is calm and inviting.",
  "Baking cookies is a delightful activity. The smell of freshly baked cookies fills the house, and the taste is always a treat. It's a fun way to spend time with family.",
  "The city is bustling with activity. There are shops to explore, restaurants to try, and sights to see. It's an exciting place full of energy and diversity.",
  "Watching a movie is a great way to relax. It allows you to immerse yourself in a story and experience different emotions. It's a perfect way to unwind.",
  "A picnic in the park is a lovely way to enjoy the outdoors. Packing a basket with sandwiches and snacks, and sitting on a blanket under the trees is delightful.",
  "Learning a new skill is challenging but rewarding. It requires patience and practice, but the sense of achievement is worth the effort.",
  "The amusement park is full of excitement. The rides are thrilling, and the games are fun. It's a place where you can let loose and enjoy yourself.",
  "Writing a letter is a personal way to communicate. It allows you to express your thoughts and feelings in a meaningful way. It's a thoughtful gesture.",
  "Walking in the rain can be refreshing. The sound of raindrops and the cool air create a peaceful atmosphere. It's a unique way to experience nature.",
  "The farmer's market is full of fresh produce and local goods. It's a great place to support local farmers and find delicious ingredients.",
  "The aquarium is a fascinating place. Watching the colorful fish and marine life is mesmerizing. It's an educational experience for all ages.",
  "Playing a musical instrument is a creative outlet. It requires practice and dedication, but the joy of making music is fulfilling.",
  "The countryside is peaceful and serene. The open fields and fresh air provide a sense of tranquility. It's a perfect escape from the city.",
  "Volunteering is a rewarding experience. It allows you to give back to the community and make a positive impact. It's a fulfilling way to spend your time.",
  "The art gallery is filled with inspiring works. Each piece tells a story and evokes emotions. It's a place to appreciate creativity and talent.",
  "A day at the spa is a relaxing treat. The massages and treatments rejuvenate the body and mind. It's a perfect way to pamper yourself.",
  "Hiking in the mountains is an adventure. The trails offer stunning views and a chance to connect with nature. It's a great way to stay active.",
  "The botanical garden is a beautiful place. The variety of plants and flowers is impressive. It's a peaceful spot to enjoy nature's beauty.",
  "Spending a day at the lake is refreshing. The water is calm, and the scenery is picturesque. It's a great place for swimming and relaxation.",
  "Visiting a historical site is educational. It provides insight into the past and helps you appreciate history. It's a valuable learning experience.",
  "Festivals are lively and fun. The music, food, and activities create a festive atmosphere. It's a great way to celebrate and enjoy with others.",
  "The planetarium is a place of wonder. The stars and planets are fascinating to learn about. It's an educational experience for all ages.",
  "A day at the farm is a hands-on experience. Feeding the animals and learning about agriculture is both fun and educational.",
  "The theater is a place of entertainment. Watching a live performance is captivating. It's a cultural experience that enriches the soul.",
  "Going to the gym is a healthy habit. The exercise equipment and classes help you stay fit. It's a great way to maintain a healthy lifestyle.",
  "The science center is full of interactive exhibits. It's a place to learn and explore scientific concepts in a fun way.",
  "The wildlife sanctuary is a haven for animals. Observing them in their natural habitat is a unique experience.",
  "The bakery is filled with delicious treats. The smell of fresh bread and pastries is irresistible. It's a delightful place to visit.",
  "The bookstore is a treasure trove of knowledge. Browsing through the shelves and discovering new books is a joy.",
  "The flower shop is a colorful place. The variety of blooms and arrangements is beautiful. It's a lovely spot to find a gift.",
  "The playground is a fun place for children. The swings, slides, and climbing structures provide endless entertainment.",
  "The ice cream parlor is a sweet treat. The variety of flavors and toppings is exciting. It's a perfect place to cool off on a hot day.",
  "Attending a concert is exhilarating. The live music and energy of the crowd create an unforgettable experience.",
  "The antique shop is full of history. Each item has a story to tell. It's a fascinating place to explore.",
  "Practicing yoga is calming. The poses and breathing exercises promote relaxation and mindfulness.",
  "The candy store is a colorful delight. The variety of sweets and treats is tempting. It's a fun place to indulge.",
  "The craft fair is full of creativity. The handmade items and unique crafts are inspiring. It's a great place to find one-of-a-kind gifts.",
  "The pet store is full of adorable animals. Watching them play and interact is heartwarming. It's a fun place to visit.",
]

export const LANGUAGES = [
  [
    "English",
    ["en-AU", "Australia"],
    ["en-CA", "Canada"],
    ["en-IN", "India"],
    ["en-NZ", "New Zealand"],
    ["en-ZA", "South Africa"],
    ["en-GB", "United Kingdom"],
    ["en-US", "United States"],
  ],
  [
    "Español",
    ["es-AR", "Argentina"],
    ["es-BO", "Bolivia"],
    ["es-CL", "Chile"],
    ["es-CO", "Colombia"],
    ["es-CR", "Costa Rica"],
    ["es-EC", "Ecuador"],
    ["es-SV", "El Salvador"],
    ["es-ES", "España"],
    ["es-US", "Estados Unidos"],
    ["es-GT", "Guatemala"],
    ["es-HN", "Honduras"],
    ["es-MX", "México"],
    ["es-NI", "Nicaragua"],
    ["es-PA", "Panamá"],
    ["es-PY", "Paraguay"],
    ["es-PE", "Perú"],
    ["es-PR", "Puerto Rico"],
    ["es-DO", "República Dominicana"],
    ["es-UY", "Uruguay"],
    ["es-VE", "Venezuela"],
  ],
  ["Français", ["fr-FR"]],
  ["Italiano", ["it-IT", "Italia"], ["it-CH", "Svizzera"]],
  ["Português", ["pt-BR", "Brasil"], ["pt-PT", "Portugal"]],
  ["日本語", ["ja-JP"]],
  ["Lingua latīna", ["la"]],
]


export const API_ROUTES = {
  TRANSCRIPTION: "/api/audio-to-speech",
  TEXT_TO_SPEECH: "/text-to-speech",
}
